### PR TITLE
[d/tfe_organization] Make `name` argument optional if configured for the provider

### PR DESCRIPTION
**Pull request by tmatilai**
## Description

The `organization` argument of all (?) other resources and data sources is already optional if defined in the provider configuration. This PR makes the `tfe_organization` data source to behave the same with the `name` argument.

It actually already fetched the "current" organization with `name = ""`, but the `name` attribute was not written back to the data source.

## Testing plan

```terraform
provider "tfe" {
  organization = "example"
}

data "tfe_organization" "current" {}
```

## Output from acceptance tests

```
$ TESTARGS="-run TestAccTFEOrganizationDataSource" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEOrganizationDataSource -timeout 15m
?       github.com/hashicorp/terraform-provider-tfe     [no test files]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/client     (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/logging    (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-tfe/version     [no test files]
=== RUN   TestAccTFEOrganizationDataSource_basic
--- PASS: TestAccTFEOrganizationDataSource_basic (4.56s)
=== RUN   TestAccTFEOrganizationDataSource_defaultProject
--- PASS: TestAccTFEOrganizationDataSource_defaultProject (3.58s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   8.358s
```

### CODE REVIEW

**Review by nfagerlund — APPROVED** [review]
Oh, funny! Yeah, okay, this seems legit. 

We should probably have a test case for omitting name, but I can follow up with that; I'll need to push a dummy commit to get CI running anyway.

**Comment by tmatilai** [comment]
Btw, seems that v0.50.0 was released, but the changelog was not updated

**Comment by nfagerlund** [comment]
Sorry, this slipped a bit when some other stuff came up and didn't make it to that last provider release — let's get it into the next one! 

To simplify getting CI passing, I'm going to rebase this into a fresh PR that includes both of the commits you authored, plus the test I wrote. I'll link back to this one for context, then close it while we move the combined PR forward.

**Comment by nfagerlund** [comment]
Superseded by #1149

**Comment by tmatilai** [comment]
No worries, this is not the most important PR. 😄

Thanks for taking care!

**Pull request closed without merging**
