### PR TITLE
fix: treat workspace deletion api errors as errors

### PR DESCRIPTION
**Pull request by skeggse**
## Description

https://github.com/hashicorp/terraform-provider-tfe/pull/675#discussion_r1065176811

### CODE REVIEW

**Review by sebasslash — APPROVED** [review]
This seems good to me, thanks for catching this. I will rebase your changes onto a local branch so we can run it against CI :+1:

**Comment by sebasslash** [comment]
See #759

**Comment by skeggse** [comment]
Thank you!

**Comment by skeggse** [comment]
Duplicate of #759.

**Pull request closed without merging**
