### PR TITLE
Update Variable & Variable Sets Documentation

### PR DESCRIPTION
**Pull request by zahiar**
## Description

Fixed incorrect workspace resource reference, should be `name` not `id`. And added docs to show how to import variable sets and variables that are part of a variable set.

### CODE REVIEW

**Comment by sebasslash** [comment]
Thank you for your contribution, however these changes have been [addressed](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CHANGELOG.md#0301-april-01-2022) and released!

**Comment by zahiar** [comment]
@sebasslash Hey, I looked at the new 0.30.1 published docs and they are sadly still missing the changes in this PR, specifically the Import section and changing this `organization  = tfe_organization.test.id` to `organization  = tfe_organization.test.name`.

**Comment by zisom-hc** [comment]
Hey Sebastian, i believe what this user was attempting to implement does not exist within the currently published documentation, in regard to their inclusion of the import command information. And in their proposal, they are saying that the example commands, where `.id` is being referred to needs to be changed to `.name` per what they have expierienced, although this should probably be confirmed.

**Review by sebasslash — APPROVED** [review]
I apologize deeply, this is in fact not a duplicate. I'll go ahead & merge and cut a `v0.30.2` release to fix this immediately.

**Comment by zahiar** [comment]
It's all good 🙂 - thanks both 👍

**Comment by sebasslash** [comment]
@zahiar would you mind taking a look at #469 and ensure everything is in order please. 'Tis very annoying we can't update documentation without cutting a new release :(

**Comment by zahiar** [comment]
Sure I'll take a look now

**Pull request merged**
