### PR TITLE
Workspace Source Name and URL

### PR DESCRIPTION
**Pull request by annawinkler**
## Description

Addresses https://github.com/hashicorp/terraform-provider-tfe/issues/392

## Testing plan

Example code:

```
resource "tfe_workspace" "test" {
  name         = "test-source"
  organization = "lmhd"
  source_name  = "TFE Provider"
  source_url   = "https://github.com/hashicorp/terraform-provider-tfe/issues/392"
}
```

(See https://github.com/hashicorp/terraform-provider-tfe/issues/392 for further tests)

## External links

- [API documentation](https://www.terraform.io/cloud-docs/api-docs/workspaces)
  - As these are listed as beta parameters, I can understand if we wish to hold off on adding support to the provider for now. On the other hand, they are already supported by the Go TFE SDK.

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See TESTS.md to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TESTARGS="-run TestAccTFEWorkspace" make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspace -timeout 15m
?   	github.com/hashicorp/terraform-provider-tfe	[no test files]
=== RUN   TestAccTFEWorkspaceIDsDataSource_basic
--- PASS: TestAccTFEWorkspaceIDsDataSource_basic (23.16s)
=== RUN   TestAccTFEWorkspaceIDsDataSource_wildcard
--- PASS: TestAccTFEWorkspaceIDsDataSource_wildcard (19.90s)
=== RUN   TestAccTFEWorkspaceIDsDataSource_tags
--- PASS: TestAccTFEWorkspaceIDsDataSource_tags (19.18s)
=== RUN   TestAccTFEWorkspaceIDsDataSource_searchByTagAndName
--- PASS: TestAccTFEWorkspaceIDsDataSource_searchByTagAndName (20.73s)
=== RUN   TestAccTFEWorkspaceIDsDataSource_empty
--- PASS: TestAccTFEWorkspaceIDsDataSource_empty (3.45s)
=== RUN   TestAccTFEWorkspaceIDsDataSource_namesEmpty
--- PASS: TestAccTFEWorkspaceIDsDataSource_namesEmpty (26.51s)
=== RUN   TestAccTFEWorkspaceRunTaskDataSource_basic
    testing.go:65: Skipping tests for Run Tasks. Set 'RUN_TASKS_URL' to enabled this tests.
--- SKIP: TestAccTFEWorkspaceRunTaskDataSource_basic (0.00s)
=== RUN   TestAccTFEWorkspaceDataSource_remoteStateConsumers
--- PASS: TestAccTFEWorkspaceDataSource_remoteStateConsumers (25.28s)
=== RUN   TestAccTFEWorkspaceDataSource_basic
--- PASS: TestAccTFEWorkspaceDataSource_basic (20.84s)
=== RUN   TestAccTFEWorkspaceRunTask_create
    testing.go:65: Skipping tests for Run Tasks. Set 'RUN_TASKS_URL' to enabled this tests.
--- SKIP: TestAccTFEWorkspaceRunTask_create (0.00s)
=== RUN   TestAccTFEWorkspaceRunTask_import
    testing.go:65: Skipping tests for Run Tasks. Set 'RUN_TASKS_URL' to enabled this tests.
--- SKIP: TestAccTFEWorkspaceRunTask_import (0.00s)
=== RUN   TestAccTFEWorkspace_basic
--- PASS: TestAccTFEWorkspace_basic (21.79s)
=== RUN   TestAccTFEWorkspace_panic
--- PASS: TestAccTFEWorkspace_panic (18.79s)
=== RUN   TestAccTFEWorkspace_monorepo
--- PASS: TestAccTFEWorkspace_monorepo (16.36s)
=== RUN   TestAccTFEWorkspace_renamed
--- PASS: TestAccTFEWorkspace_renamed (29.48s)
=== RUN   TestAccTFEWorkspace_update
--- PASS: TestAccTFEWorkspace_update (25.68s)
=== RUN   TestAccTFEWorkspace_updateWorkingDirectory
--- PASS: TestAccTFEWorkspace_updateWorkingDirectory (32.28s)
=== RUN   TestAccTFEWorkspace_updateFileTriggers
--- PASS: TestAccTFEWorkspace_updateFileTriggers (19.76s)
=== RUN   TestAccTFEWorkspace_updateTriggerPrefixes
--- PASS: TestAccTFEWorkspace_updateTriggerPrefixes (26.69s)
=== RUN   TestAccTFEWorkspace_changeTags
--- PASS: TestAccTFEWorkspace_changeTags (73.04s)
=== RUN   TestAccTFEWorkspace_updateSpeculative
--- PASS: TestAccTFEWorkspace_updateSpeculative (19.19s)
=== RUN   TestAccTFEWorkspace_structuredRunOutputDisabled
--- PASS: TestAccTFEWorkspace_structuredRunOutputDisabled (18.97s)
=== RUN   TestAccTFEWorkspace_updateVCSRepo
    resource_tfe_workspace_test.go:556: Please set GITHUB_TOKEN to run this test
--- SKIP: TestAccTFEWorkspace_updateVCSRepo (0.55s)
=== RUN   TestAccTFEWorkspace_sshKey
--- PASS: TestAccTFEWorkspace_sshKey (28.93s)
=== RUN   TestAccTFEWorkspace_import
--- PASS: TestAccTFEWorkspace_import (14.71s)
=== RUN   TestAccTFEWorkspace_importVCSBranch
    resource_tfe_workspace_test.go:706: Please set GITHUB_TOKEN to run this test
--- SKIP: TestAccTFEWorkspace_importVCSBranch (0.47s)
=== RUN   TestAccTFEWorkspace_operationsAndExecutionModeInteroperability
    resource_tfe_workspace_test.go:750: Step 5/5 error: Error running apply: exit status 1

        Error: Error creating agent pool agent-pool-test for organization tst-terraform-3886321602341347244: resource not found

          with tfe_agent_pool.foobar,
          on terraform_plugin_test.tf line 7, in resource "tfe_agent_pool" "foobar":
           7: resource "tfe_agent_pool" "foobar" {

--- FAIL: TestAccTFEWorkspace_operationsAndExecutionModeInteroperability (35.04s)
=== RUN   TestAccTFEWorkspace_globalRemoteState
--- PASS: TestAccTFEWorkspace_globalRemoteState (17.85s)
=== RUN   TestAccTFEWorkspace_alterRemoteStateConsumers
    resource_tfe_workspace_test.go:865: Step 1/5 error: Check failed: Check 2/2 error: tfe_workspace.foobar: Attribute 'global_remote_state' expected "true", got "false"
--- FAIL: TestAccTFEWorkspace_alterRemoteStateConsumers (7.50s)
=== RUN   TestAccTFEWorkspace_createWithRemoteStateConsumers
--- PASS: TestAccTFEWorkspace_createWithRemoteStateConsumers (10.43s)
=== RUN   TestAccTFEWorkspace_paginatedRemoteStateConsumers
--- PASS: TestAccTFEWorkspace_paginatedRemoteStateConsumers (73.65s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-tfe/tfe	652.987s
?   	github.com/hashicorp/terraform-provider-tfe/version	[no test files]
FAIL
make: *** [testacc] Error 1
...
```

i.e. there was a failure... but not in resources I've modified

### CODE REVIEW

**Review by brandonc — APPROVED** [review]
Code looks good but I did not smoke test

**Comment by annawinkler** [comment]
Smoke tested with a local TFE provider build with the following config (I created the workspace first and then ran terraform apply:

```

terraform {
  required_providers {
    tfe = {
      version = "~> 0.42.0"
    }
  }
}

resource "tfe_workspace" "test" {
  name         = "test-source"
  organization = "annas-bananas"
  source_name  = "TFE Provider"
  source_url   = "https://github.com/hashicorp/terraform-provider-tfe/issues/392"
}

data "tfe_workspace" "test" {
  name = "test-source"
  organization = "annas-bananas"
}

output "tfe_workspace_source_name" {
  value = data.tfe_workspace.test.source_name
}

output "tfe_workspace_source_url" {
  value = data.tfe_workspace.test.source_url
}

```

Outputs have expected values:

Screenshot 2023-02-02 at 6 17 42 PM

**Comment by annawinkler** [comment]
The most recent test failures could be because of the code changes - @lucymhdavies we could take a look next week.

**Comment by nfagerlund** [comment]
These feel more like attributes that were intended to be hardcoded into the provider (or something that sits at a similar level of integration). But I guess there's an argument to be made for treating _a specific terraform config_ as the "application" that created the workspace. Actually, the tflocal-cloud workspaces we use to manage CI instances for this repo might have benefited from this. 

Anyway, they're odd, but I guess I'm in favor. 👍🏼

**Comment by lucymhdavies** [comment]
> These feel more like attributes that were intended to be hardcoded into the provider (or something that sits at a similar level of integration).

As I understand, these attributes exist in the API mostly for the ServiceNow integration. e.g. so you can see that a workspace was created by a particular SNOW request.

I want them in the TFE provider so I can create a workspace and have that workspace link back to the exact file in GitHub where I'm declaring that workspace. Or link to the parent workspace that created it. All sorts of things like that are possible.

I do like the idea of some default values hardcoded into the provider... but the main concern there is that these parameters of the workspace cannot be updated after a workspace already exists; they can only be set when the workspace is first created. So we'd need the API to be updated to allow these values to be modified after a workspace is already created.

This is something I'm calling out in the docs actually, as updating these `source_*` fields will currently cause the provider to want to recreate the workspace:
https://github.com/hashicorp/terraform-provider-tfe/pull/783/files#diff-bfbce643fcc0ab61982517da2ace62b273bab85cb2536b7d8a9dc92aacedb068R99-R101

It's been a while since I initially wrote the PR. At the time I was worried that calling it out here wasn't sufficient warning. But now... given that by default the TFE provider will only try to do a Safe Delete on a workspace... we've probably prevented any footguns that could happen as a result of adding these `source_*` fields after a workspace has already been created.



So.... TL;DR: agreed with the idea that these seem like they should have default values within the provider, but until the API has been updated to allow modifying these values on an existing workspace, I don't think we can really do that yet (without making the code unnecessarily complex)

**Pull request merged**
