### PR TITLE
bump minor release in README

### PR DESCRIPTION
**Pull request by mbevc1**
## Description

Align README with current release version.

_Remember to:_

- _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CONTRIBUTING.md#updating-the-changelog)_

- _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CONTRIBUTING.md#updating-the-documentation)_

## Testing plan

1.  _Describe how to replicate_
1.  _the conditions_
1.  _under which your code performs its purpose,_
1.  _including example Terraform configs where necessary._

## External links

_Include any links here that might be helpful for people reviewing your PR. If there are none, feel free to delete this section._

- [go-tfe documentation](https://pkg.go.dev/github.com/hashicorp/go-tfe?tab=doc#xxxx)
- [API documentation](https://www.terraform.io/docs/cloud/api/xxxx.html)
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/xxxx)

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See TESTS.md to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TESTARGS="-run TestAccTFEWorkspace" make testacc

...
```

### CODE REVIEW

**Review by sebasslash — CHANGES_REQUESTED** [review]
Thank you for this :heart:, will approve pending removal of the changelog entry (not necessary!).

**Comment by mbevc1** [comment]
Cool, sorted!

**Comment by annawinkler** [comment]
Thank you for opening this PR. We released 0.37.0 and all of the docs have been updated (I hope!). I'm going to close out this PR.

**Comment by mbevc1** [comment]
Thanks for updating this in the latest release! Was there a reason not merging this PR or are you not open to external contributions?

**Comment by annawinkler** [comment]
@mbevc1 Sorry about that - we are open to external contributions and we've been discussing how best to support external contributions with security concerns. We're hoping to figure out a way forward over the next few weeks.

**Comment by mbevc1** [comment]
Okay, hope this will be documented so changes could be submitted accordingly.

**Comment by annawinkler** [comment]
I agree! 🎉

**Pull request closed without merging**
