### PR TITLE
Update changelog to v0.30.2 (unreleased)

### PR DESCRIPTION
**Pull request by sebasslash**

### CODE REVIEW

**Review by uturunku1 — APPROVED** [review]
🤞

**Comment by zahiar** [comment]
@sebasslash Looks to be missing a fair few changes from #466 like the import sections on both variable & variable_set resources 😢

**Comment by zahiar** [comment]
> @sebasslash Looks to be missing a fair few changes from #466 like the import sections on both variable & variable_set resources 😢

Actually, looking at previous Changelog PRs this is fine, I got caught out by the additional `organization = tfe_organization.test.name` 🙈

**Comment by sebasslash** [comment]
No worries, your changes are there! This was simply to verify the changelog was correctly worded. I noticed a few organization attributes were being referenced by `id` instead of `name` so I changed them. Although in practice `name` and `id` are interchangeable for organizations.

**Comment by zahiar** [comment]
Cool, we actually found the opposite in our case, `id` & `name` were not interchangeable - it led to errors as `id` was some generated value.

**Comment by sebasslash** [comment]
That's very interesting and I'll keep that in mind for our future effort to bring the provider to 1.0.

**Pull request merged**
